spring:
  application:
    name: pedidos
  datasource:
    url: jdbc:postgresql://localhost:5555/erppedidos
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8083

erpmicroservices:
  pedido:
    clients:
      produtos:
        url: 'http://localhost:8081/produtos'
      clientes:
        url: 'http://localhost:8082/clientes'
    webhook:
      api-key: 'API_KEY_TESTE_123'
  config:
    kafka:
      consumer:
        group-id: 'erp-atualizacao-pedido'
      server-url: 'http://localhost:29092'
      topics:
        pedidos-pagos: 'erp.pedidos-pagos'
        pedidos-faturados: 'erp.pedidos-faturados'
        pedidos-enviados: 'erp.pedidos-enviados'