spring:
  application:
    name: faturamento

erpmicroservices:
  config:
    kafka:
      server-url: 'http://localhost:29092'
      group-id: 'erp-faturamento'
      topics:
        pedidos-pagos: 'erp.pedidos-pagos'
        pedidos-faturas: 'erp.pedidos-faturados'

server:
  port: 8084

minio:
  url: 'http://localhost:9100'
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: erp.faturas