spring:
  application:
    name: faturamento

erpmicroservices:
  config:
    kafka:
      topics:
        pedidos-pagos: 'erp.pedidos-pagos'

server:
  port: 8084

minio:
  url: 'http://localhost:9100'
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: erp.faturas